name: Docs

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress --include-verbatim 'docs/**/*.md'
          fail: true
