import { themes as prismThemes } from 'prism-react-renderer';
import type { Config } from '@docusaurus/types';
import type * as Preset from '@docusaurus/preset-classic';

// docs/website/react/ — Docusaurus + TypeDoc + Storybook documentation
// dashboard for the github-pages repository. See ./README.md for how the
// three tools fit together and ../README.md for what's on the site.

const config: Config = {
  title: 'github-pages Docs',
  tagline: "ACFHarbinger's personal site — architecture, guides, and component reference",
  favicon: 'img/favicon.ico',

  future: {
    v4: true,
  },

  // Deployed alongside the main site under a /docs-site/ subpath so it
  // doesn't collide with the primary Next.js static export's gh-pages
  // deployment — see ../README.md for the deployment note.
  url: 'https://acfharbinger.github.io',
  baseUrl: '/github-pages/docs-site/',

  organizationName: 'ACFHarbinger',
  projectName: 'github-pages',

  onBrokenLinks: 'warn',
  onBrokenMarkdownLinks: 'warn',

  markdown: {
    // The repo's docs/*.md are plain CommonMark, read directly by other
    // tools too (GitHub, plain editors) — `.md` files here render as plain
    // Markdown (no JSX/expression parsing), while any `.mdx` added later
    // still gets full MDX. Without this, MDX 3's stricter parser chokes on
    // ordinary Markdown constructs (e.g. a `{...}` in prose or a fenced
    // code block containing a function declaration) as if they were JS.
    format: 'detect',
  },

  i18n: {
    defaultLocale: 'en',
    locales: ['en'],
  },

  presets: [
    [
      'classic',
      {
        docs: {
          id: 'default',
          path: '../../',
          routeBasePath: 'docs',
          include: [
            '*.md',
            'adr/*.md',
            'moon/*.md',
            'moon/roadmaps/*.md',
            'moon/research/*.md',
            'moon/reports/*.md',
            // Generated by TypeDoc into docs/website/react/api-docs/ (see
            // ../README.md, `npm run gen:api`). This has to be owned by
            // *this* plugin instance (not e.g. a "guides" instance whose
            // own `path` is the repo root) because it's physically nested
            // under this plugin's `path` (docs/) regardless of which
            // instance's `include` lists it — a docs-plugin instance whose
            // include lists a file actually rooted under a *different*
            // instance's path breaks Docusaurus's plugin-ownership
            // resolution used when generating webpack imports for that
            // file ("Cannot find module '.../default/...'" for a file that
            // exists under a different, correctly-generated plugin folder).
            'website/react/api-docs/**/*.md',
          ],
          sidebarPath: './sidebars.ts',
          editUrl: 'https://github.com/ACFHarbinger/github-pages/tree/main/docs/',
        },
        blog: false,
        theme: {
          customCss: './src/css/custom.css',
        },
      } satisfies Preset.Options,
    ],
  ],

  plugins: [
    [
      '@docusaurus/plugin-content-docs',
      {
        id: 'guides',
        path: '../../../',
        routeBasePath: 'guides',
        include: ['README.md', 'git/CONTRIBUTING.md', '.agent/AGENTS.md'],
        sidebarPath: './sidebarsGuides.ts',
        editUrl: 'https://github.com/ACFHarbinger/github-pages/tree/main/',
      },
    ],
  ],

  themeConfig: {
    image: 'img/docusaurus-social-card.jpg',
    colorMode: {
      defaultMode: 'dark',
      respectPrefersColorScheme: true,
    },
    navbar: {
      title: 'github-pages',
      logo: {
        alt: 'github-pages logo',
        src: 'img/logo.svg',
      },
      items: [
        { type: 'docSidebar', sidebarId: 'docsSidebar', docsPluginId: 'default', position: 'left', label: 'Docs' },
        { type: 'docSidebar', sidebarId: 'guidesSidebar', docsPluginId: 'guides', position: 'left', label: 'Guides' },
        { type: 'docSidebar', sidebarId: 'apiSidebar', docsPluginId: 'default', position: 'left', label: 'API Reference' },
        { to: '/storybook/index.html', label: 'Storybook', position: 'left' },
        {
          href: 'https://github.com/ACFHarbinger/github-pages',
          label: 'GitHub',
          position: 'right',
        },
        {
          href: 'https://acfharbinger.github.io/github-pages/',
          label: 'Live Site ↗',
          position: 'right',
        },
      ],
    },
    footer: {
      style: 'dark',
      links: [
        {
          title: 'Documentation',
          items: [
            { label: 'Architecture', to: '/docs/ARCHITECTURE' },
            { label: 'Roadmap', to: '/docs/moon/ROADMAP' },
            { label: 'Changelog', to: '/docs/moon/CHANGELOG' },
          ],
        },
        {
          title: 'Reference',
          items: [
            { label: 'API Reference', to: '/docs/website/react/api-docs' },
            { label: 'Storybook', to: '/storybook/index.html' },
            { label: 'Guides', to: '/guides' },
          ],
        },
        {
          title: 'More',
          items: [
            { label: 'Live Site', href: 'https://acfharbinger.github.io/github-pages/' },
            { label: 'GitHub', href: 'https://github.com/ACFHarbinger/github-pages' },
          ],
        },
      ],
      copyright: `Copyright © ${new Date().getFullYear()} ACFHarbinger. Built with Docusaurus, TypeDoc, and Storybook.`,
    },
    prism: {
      theme: prismThemes.github,
      darkTheme: prismThemes.dracula,
      additionalLanguages: ['bash', 'json', 'yaml', 'python', 'diff'],
    },
  } satisfies Preset.ThemeConfig,
};

export default config;
