import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Explicit rather than autogenerated so ordering/grouping doesn't depend on
// adding Docusaurus-specific frontmatter (sidebar_position, _category_.json)
// to the shared repo docs/ files this reads directly — those files are also
// read plainly on GitHub and by other tooling, so they stay untouched.
const sidebars: SidebarsConfig = {
  docsSidebar: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: [
        'ARCHITECTURE',
        'DEVELOPMENT',
        'TESTING',
        'DEPENDENCIES',
        'DEPENDENCY_POLICY',
        'DOCUMENTATION_STANDARDS',
        'GLOSSARY',
        'BENCHMARKS',
        'TROUBLESHOOTING',
      ],
    },
    {
      type: 'category',
      label: 'Architecture Decisions',
      // Docusaurus strips numeric "NNNN-" prefixes from doc ids by default,
      // so the file adr/0001-record-architecture-decisions.md gets the id
      // below, not its full filename.
      items: ['adr/record-architecture-decisions'],
    },
    {
      type: 'category',
      label: 'Roadmap',
      items: [
        'moon/ROADMAP',
        'moon/CHANGELOG',
        {
          type: 'category',
          label: 'Feature Roadmaps',
          items: [
            'moon/roadmaps/user_interface',
            'moon/roadmaps/interactive_features',
            'moon/roadmaps/mathematical_optimization',
            'moon/roadmaps/machine_learning',
            'moon/roadmaps/documentation',
            'moon/roadmaps/infrastructure_and_testing',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Research',
      items: [
        'moon/research/Global Interactive Portfolio Website Architecture',
        'moon/research/Advanced Web Portfolio Architecture Research',
        'moon/reports/Website Preferences and Advanced Technologies',
      ],
    },
  ],
  // Generated by TypeDoc (see ../README.md, `npm run gen:api`) — must stay
  // on this ("default") plugin instance rather than e.g. "guides", since
  // docs/website/react/api-docs/ is physically nested under this plugin's
  // `path` (docs/) regardless of which instance's `include` lists it.
  apiSidebar: [
    'website/react/api-docs/index',
    {
      type: 'category',
      label: 'Functions',
      items: [
        'website/react/api-docs/functions/getAllPageSlugs',
        'website/react/api-docs/functions/getAllPostSlugs',
        'website/react/api-docs/functions/getMarkdownData',
        'website/react/api-docs/functions/parseSlug',
      ],
    },
    {
      type: 'category',
      label: 'Interfaces',
      items: ['website/react/api-docs/interfaces/PostData'],
    },
  ],
};

export default sidebars;
