import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import type { StorybookConfig } from '@storybook/react-vite';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Storybook for the actual site components at ../../../../src/components/ —
// stories import them directly (see ../stories/), no copy or symlink
// involved. See ../README.md for how this fits with Docusaurus/TypeDoc.
const config: StorybookConfig = {
    stories: ['../stories/**/*.stories.@(ts|tsx)'],
    addons: ['@storybook/addon-docs', '@storybook/addon-a11y'],
    framework: {
        name: '@storybook/react-vite',
        options: {},
    },
    typescript: {
        // Component prop tables (the "Docs" tab / autodocs) are meant to be
        // generated by react-docgen-typescript, not the default lighter
        // react-docgen — this is the "TypeDoc with react-docgen-typescript"
        // half of the stack for component props specifically (TypeDoc
        // itself documents lib/'s plain TS exports; see ../typedoc.json).
        // In practice it never attaches docgen info here regardless of how
        // the component files are imported — see ../README.md's "Known
        // limitation" note — so every story ships hand-written argTypes
        // instead. Left configured in case a future Storybook/plugin
        // version fixes it.
        reactDocgen: 'react-docgen-typescript',
    },
    async viteFinal(viteConfig) {
        const root = path.resolve(__dirname, '../../../../');
        viteConfig.resolve ??= {};
        viteConfig.resolve.alias = {
            ...(viteConfig.resolve.alias ?? {}),
            'next/image': path.resolve(__dirname, 'shims/next-image.tsx'),
            'next/link': path.resolve(__dirname, 'shims/next-link.tsx'),
            'next/navigation': path.resolve(__dirname, 'shims/next-navigation.ts'),
            '@/assets/images/23041868.jpeg': path.resolve(__dirname, 'shims/profile-pic.ts'),
            '@': root,
        };
        // Inline PostCSS/Tailwind config (not a root postcss.config.js) so
        // Docusaurus's separate webpack build never picks this up — see
        // ../tailwind.config.cjs's module doc comment.
        viteConfig.css ??= {};
        viteConfig.css.postcss = {
            plugins: [tailwindcss(require('../tailwind.config.cjs')), autoprefixer],
        };
        return viteConfig;
    },
};

export default config;
