import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import type { StorybookConfig } from '@storybook/react-vite';
import tailwindcss from 'tailwindcss';
import autoprefixer from 'autoprefixer';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const require = createRequire(import.meta.url);

// Storybook for the actual site components at ../../../src/components/ —
// this project doesn't duplicate them, it just points Vite/react-docgen at
// the real sources. See ../README.md for how this fits with Docusaurus/TypeDoc.
const config: StorybookConfig = {
    stories: ['../stories/**/*.stories.@(ts|tsx)'],
    addons: ['@storybook/addon-docs', '@storybook/addon-a11y'],
    framework: {
        name: '@storybook/react-vite',
        options: {},
    },
    typescript: {
        // Component prop tables (the "Docs" tab / autodocs) are generated by
        // react-docgen-typescript, not the default lighter react-docgen —
        // this is the "TypeDoc with react-docgen-typescript" half of the
        // stack for component props specifically (TypeDoc itself documents
        // lib/'s plain TS exports; see ../typedoc.json).
        reactDocgen: 'react-docgen-typescript',
    },
    async viteFinal(viteConfig) {
        const root = path.resolve(__dirname, '../../../../');
        viteConfig.resolve ??= {};
        // Keep the site-src/ symlink as the module id Vite/Rollup sees,
        // rather than resolving it to its ../../../src real path — that
        // real path is what the react-docgen-typescript project-boundary
        // check above the alias map rejects.
        viteConfig.resolve.preserveSymlinks = true;
        // An explicit array (not an object) so match order is guaranteed —
        // spreading an existing alias *object* and re-declaring some of its
        // keys does not actually move those keys later in iteration order
        // (a key's position is set by its first occurrence), which silently
        // let the generic "@" fallback win over "@/site-src" below when
        // this was an object literal.
        const existingAlias = viteConfig.resolve.alias;
        const existingAliasEntries = Array.isArray(existingAlias)
            ? existingAlias
            : Object.entries(existingAlias ?? {}).map(([find, replacement]) => ({ find, replacement }));
        viteConfig.resolve.alias = [
            { find: 'next/image', replacement: path.resolve(__dirname, 'shims/next-image.tsx') },
            { find: 'next/link', replacement: path.resolve(__dirname, 'shims/next-link.tsx') },
            { find: 'next/navigation', replacement: path.resolve(__dirname, 'shims/next-navigation.ts') },
            { find: '@/assets/images/23041868.jpeg', replacement: path.resolve(__dirname, 'shims/profile-pic.ts') },
            // `site-src/` is a symlink (`ln -s ../../../src site-src`, see
            // ../README.md) to the real src/ — imported through it rather
            // than through the `@` alias below so react-docgen-typescript
            // sees these files as *inside* this project directory. The
            // vite-plugin-react-docgen-typescript used by @storybook/react-vite
            // silently skips docgen ("not included in the active TypeScript
            // project") for any file outside the project root even when a
            // tsconfig covering it is passed explicitly — this sidesteps
            // that rather than fighting it further.
            { find: '@/src', replacement: path.resolve(__dirname, '../site-src') },
            { find: '@', replacement: root },
            ...existingAliasEntries,
        ];
        // Inline PostCSS/Tailwind config (not a root postcss.config.js) so
        // Docusaurus's separate webpack build never picks this up — see
        // ../tailwind.config.cjs's module doc comment.
        viteConfig.css ??= {};
        viteConfig.css.postcss = {
            plugins: [tailwindcss(require('../tailwind.config.cjs')), autoprefixer],
        };
        return viteConfig;
    },
};

export default config;
